// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqfrcnelxlfivjpsimfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxZnJjbmVseGxmaXZqcHNpbWZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2MDQ1MjQsImV4cCI6MjA2NjE4MDUyNH0.N1Kuy-eI6PVhKluW9ABBpYEDnOg1DxIL4YcpiEYDVkY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);